# This rule is not used by the project fanet-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to fanet.restart.eu resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fanet-operator
    app.kubernetes.io/managed-by: kustomize
  name: uav-viewer-role
rules:
- apiGroups:
  - fanet.restart.eu
  resources:
  - uavs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fanet.restart.eu
  resources:
  - uavs/status
  verbs:
  - get
